import Script from "next/script";
import './CSS/normalize.css';
import './CSS/icomoon.css';
import './CSS/vendor.css';
import './CSS/globals.css';
import './CSS/styleMain.css';
import './CSS/searchPopup.css';
import './CSS/styleBootstrap.css';
import './CSS/header.css';
import Header from './Components/Header';
import Footer from './Components/Footer';

export const metadata = {
  title: "Shop Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <Header />

        {children}

        <Footer />
        
        <Script src="/js/jquery-1.11.0.min.js" />
        <Script src="/js/plugins.js" />
        <Script src="/js/script.js" />
      </body>
    </html>
  );
}
